// File generated by FlutterFire CLI for project: riau-education
// flutterfire configure --project=riau-education

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrMmL2QDivGxoDvMzDDtGQwKx6SCcXS4',
    appId: '1:83128997767:web:8c742951173ff9e3dc2522',
    messagingSenderId: '83128997767',
    projectId: 'riau-education',
    authDomain: 'riau-education.firebaseapp.com',
    storageBucket: 'riau-education.firebasestorage.app',
    measurementId: 'G-LE7VYDWY53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fTx2ST8LfwIZSTQ_UiGOqXOF1YEUb_4',
    appId: '1:83128997767:android:e625a509328f00b7dc2522',
    messagingSenderId: '83128997767',
    projectId: 'riau-education',
    storageBucket: 'riau-education.firebasestorage.app',
  );

  // Windows uses Web configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbrMmL2QDivGxoDvMzDDtGQwKx6SCcXS4',
    appId: '1:83128997767:web:8c742951173ff9e3dc2522',
    messagingSenderId: '83128997767',
    projectId: 'riau-education',
    authDomain: 'riau-education.firebaseapp.com',
    storageBucket: 'riau-education.firebasestorage.app',
    measurementId: 'G-LE7VYDWY53',
  );
}
